# Generated by Django 4.2 on 2025-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name_1', models.CharField(max_length=50)),
                ('last_name_2', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('enrolled_modules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name_1', models.TextField()),
                ('last_name_2', models.TextField()),
                ('email', models.TextField()),
                ('course', models.TextField()),
                ('tutor', models.BooleanField(default=False)),
                ('teaching_modules', models.TextField()),
            ],
        ),
    ]
